import {test,expect} from '@playwright/test'
import {writeFileSync} from 'node:fs'
import {create,card} from './helpers'
const shot=(page,name)=>page.screenshot({path:`docs/screenshots/${name}.png`,fullPage:true,animations:'disabled'})
test('最终验收：功能截图、主题双向持久化、演示数据及无控制台错误',async({page,context})=>{
 test.setTimeout(60000)
 const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())})
 await page.goto('/');await shot(page,'17-empty-state');
 await page.getByRole('button',{name:'＋ 新建任务',exact:true}).click();await shot(page,'02-create-form');await page.getByRole('button',{name:'创建任务',exact:true}).click();await expect(page.getByRole('alert')).toContainText('请输入任务标题');await shot(page,'03-title-validation');await page.getByLabel('任务标题').fill('完成软件工程报告');await page.getByRole('button',{name:'创建任务',exact:true}).click();await expect(card(page,'完成软件工程报告')).toContainText('暂无描述');await shot(page,'04-created-without-description');
 await create(page,'整理课堂演示材料','演示顺序：创建任务、查看详情、编辑内容、取消与确认删除。\n随后展示看板拖拽、深色模式与刷新恢复。\n最后打开 Git 历史、提示词设计和截图索引，说明每轮验收结果。','in_progress','medium');
 await create(page,'搭建 Vue 项目骨架','已完成 Vite 和 Tailwind 配置，浏览器启动验证通过。','done','low');
 await card(page,'整理课堂演示材料').getByRole('button',{name:'详情',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('说明每轮验收结果');await shot(page,'05-task-details');await page.getByRole('button',{name:'关闭',exact:true}).click();
 const target=card(page,'完成软件工程报告');const id=await target.getAttribute('data-task-id');await target.getByRole('button',{name:'编辑',exact:true}).click();await shot(page,'06-edit-before');await page.getByLabel('描述').fill('补齐 F01—F09 验收表，检查每项功能的真实截图。');await page.getByLabel('优先级',{exact:true}).selectOption('high');await page.getByRole('button',{name:'保存修改'}).click();await expect(target).toHaveAttribute('data-task-id',id);await expect(target).toContainText('高优先级');await shot(page,'07-edit-after');
 await shot(page,'01-overview-light');await shot(page,'10-priorities');
 await create(page,'移除重复的演示草稿');await card(page,'移除重复的演示草稿').getByRole('button',{name:'删除',exact:true}).click();await shot(page,'08-delete-confirm');await page.getByRole('button',{name:'确认删除'}).click();await expect(page.locator('article')).toHaveCount(3);await shot(page,'09-delete-after');
 await page.getByRole('button',{name:'看板视图'}).click();await shot(page,'11-board-before-drag');const s=await target.boundingBox(),t=await page.locator('[data-column="in_progress"]').boundingBox();await page.mouse.move(s.x+s.width/2,s.y+12);await page.mouse.down();await page.mouse.move(s.x+s.width/2+15,s.y+20,{steps:5});await page.mouse.move(t.x+t.width/2,t.y+90,{steps:20});await page.mouse.move(t.x+t.width/2,t.y+95,{steps:3});await page.mouse.up();await expect(page.locator('[data-column="in_progress"]')).toContainText('完成软件工程报告');await expect(page.locator('article')).toHaveCount(3);await shot(page,'12-board-after-drag');
 await page.getByRole('button',{name:'深色模式'}).click();await expect(page.locator('html')).toHaveClass('dark');await shot(page,'13-dark-mode');const saved=await page.evaluate(()=>localStorage.getItem('xushi.tasks.v1'));await page.reload();await expect(page.locator('html')).toHaveClass('dark');expect(await page.evaluate(()=>localStorage.getItem('xushi.tasks.v1'))).toBe(saved);await page.getByRole('button',{name:'看板视图'}).click();await shot(page,'14-theme-after-reload');
 await page.getByRole('button',{name:'＋ 新建任务',exact:true}).click();await shot(page,'18-dark-form');await page.getByRole('button',{name:'取消',exact:true}).click();await page.getByRole('button',{name:'浅色模式'}).click();await expect(page.locator('html')).not.toHaveClass('dark');await page.getByRole('button',{name:'列表视图'}).click();await shot(page,'15-data-before-reload');await page.reload();await expect(page.locator('article')).toHaveCount(3);await expect(target).toContainText('进行中');await shot(page,'16-data-after-reload');
 await page.getByRole('button',{name:'深色模式'}).click();const reopened=await context.newPage();await reopened.goto('/');await expect(reopened.locator('html')).toHaveClass('dark');await expect(reopened.locator('article')).toHaveCount(3);await reopened.close();expect(errors).toEqual([]);writeFileSync('docs/test-results/browser-console.json',JSON.stringify({browser:'Chrome',pageErrorsAndConsoleErrors:errors,result:'通过'},null,2));
})
test('最终验收：窄屏、长文本、普通文本安全与主题写入失败',async({page})=>{
 await page.goto('/');const title='长文本检查：'+ '前端任务管理与软件工程验收'.repeat(12);const description='<script>alert("不是代码")</script>\n'+ '完整说明不应被截掉。'.repeat(100);await create(page,title,description);await page.setViewportSize({width:390,height:844});await expect(card(page,title)).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await shot(page,'19-mobile-list');await card(page,title).getByRole('button',{name:'详情',exact:true}).click();await expect(page.getByRole('dialog')).toContainText(description);await shot(page,'20-long-text');await page.getByRole('button',{name:'关闭弹窗'}).click();await page.getByRole('button',{name:'看板视图'}).click();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.locator('[data-column="done"]').scrollIntoViewIfNeeded();await expect(page.locator('[data-column="done"]')).toBeVisible();
 await page.evaluate(()=>{Storage.prototype.setItem=()=>{throw Error('quota')}});await page.getByRole('button',{name:'深色模式'}).click();await expect(page.getByRole('alert')).toContainText('主题保存失败');await expect(page.locator('html')).not.toHaveClass('dark');
})
test('最终验收：结构异常和读取失败不白屏',async({page})=>{
 await page.goto('/');await page.evaluate(()=>localStorage.setItem('xushi.tasks.v1','{"invalid":true}'));await page.reload();await expect(page.getByRole('heading',{name:'我的任务'})).toBeVisible();await expect(page.getByRole('alert')).toContainText('原始存储已保留');expect(await page.evaluate(()=>localStorage.getItem('xushi.tasks.v1'))).toBe('{"invalid":true}');await shot(page,'21-storage-error');
 await page.addInitScript(()=>{Storage.prototype.getItem=()=>{throw new DOMException('denied','SecurityError')}});await page.reload();await expect(page.getByRole('heading',{name:'我的任务'})).toBeVisible();await expect(page.getByRole('alert').filter({hasText:'无法读取本地任务'})).toBeVisible();
})
